/**
 * One-off generator for the per-character width table in
 * `src/components/markdown-view/diagram/textMetrics.ts`.
 *
 * The diagram layout core is DOM-free by design, so it cannot call
 * `measureText`. This script does it once, in a real browser, against the
 * real font file `@fontsource-variable/inter` ships, and prints the
 * constants to paste back into the table.
 *
 * Run from the repo root:
 *   node packages/@alepha/ui/scripts/measure-font.mjs
 *
 * The font face and size it measures MUST stay identical to
 * DIAGRAM_FONT_FAMILY / DIAGRAM_FONT_SIZE, or text and box disagree.
 */
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";

import { chromium } from "@playwright/test";

const require = createRequire(import.meta.url);
const fontPath =
  require.resolve("@fontsource-variable/inter/files/inter-latin-wght-normal.woff2");
const fontBase64 = readFileSync(fontPath).toString("base64");

const SIZE = 13;
// Every printable ASCII code point, plus the punctuation an agent-written
// label actually contains. Anything outside this set falls back to the
// average width recorded alongside the table.
const CHARS = [
  ...Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)),
  "…",
  "→",
  "←",
  "·",
  "—",
  "’",
  "“",
  "”",
  "é",
  "è",
  "à",
  "ç",
  "ü",
  "ö",
  "ñ",
];

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<!doctype html><meta charset="utf-8"><body></body>`);

const result = await page.evaluate(
  async ({ fontBase64, size, chars }) => {
    const face = new FontFace(
      "InterMeasure",
      `url(data:font/woff2;base64,${fontBase64}) format('woff2')`,
    );
    await face.load();
    document.fonts.add(face);
    await document.fonts.ready;

    const ctx = document.createElement("canvas").getContext("2d");
    ctx.font = `${size}px InterMeasure`;

    const widths = {};
    for (const char of chars) widths[char] = ctx.measureText(char).width;
    return {
      widths,
      samples: {
        MarkdownView: ctx.measureText("MarkdownView").width,
        Start: ctx.measureText("Start").width,
        "the quick brown fox": ctx.measureText("the quick brown fox").width,
      },
    };
  },
  { fontBase64, size: SIZE, chars: CHARS },
);

await browser.close();

// Bucket by rounded width so the table is a handful of groups rather than
// 110 magic numbers. Widths are stored as a RATIO of the font size, which is
// what makes the table scale to any size the emitter picks.
const buckets = new Map();
for (const [char, width] of Object.entries(result.widths)) {
  const ratio = Math.round((width / SIZE) * 1000) / 1000;
  if (!buckets.has(ratio)) buckets.set(ratio, []);
  buckets.get(ratio).push(char);
}

const rows = [...buckets.entries()].sort((a, b) => a[0] - b[0]);
const escapeQuotes = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

console.log(
  `// Generated by scripts/measure-font.mjs against Inter at ${SIZE}px.`,
);
console.log("const WIDTH_BUCKETS: Array<[ratio: number, chars: string]> = [");
for (const [ratio, chars] of rows) {
  console.log(`  [${ratio}, "${escapeQuotes(chars.join(""))}"],`);
}
console.log("];");

const average =
  Object.values(result.widths).reduce((a, b) => a + b, 0) /
  Object.values(result.widths).length /
  SIZE;
console.log(`const FALLBACK_RATIO = ${Math.round(average * 1000) / 1000};`);
console.log("// samples:", JSON.stringify(result.samples));
