import type { R2Bucket, R2UploadedPart } from "@cloudflare/workers-types";
import {
  $env,
  $hook,
  $inject,
  Alepha,
  AlephaError,
  type FileLike,
  z,
} from "alepha";
import { CryptoProvider } from "alepha/crypto";
import { $logger } from "alepha/logger";
import { currentTenantAtom } from "alepha/security";
import { FileDetector } from "alepha/system";
import { FileNotFoundError } from "../errors/FileNotFoundError.ts";
import { MultipartChunker } from "../helpers/MultipartChunker.ts";
import type { FileStorageProvider } from "./FileStorageProvider.ts";

// ---------------------------------------------------------------------------------------------------------------------

/**
 * Cloudflare R2 storage provider.
 *
 * Uses a single R2 bucket binding for every container.
 * Files are organized as: {APP_NAME}/{tenantId}/{container}/{fileId}
 *
 * **Required environment variables:**
 * - `R2_BUCKET_NAME` - The actual R2 bucket name in Cloudflare
 *
 * **Optional (uses core Alepha env):**
 * - `APP_NAME` - Prefix for all files (for multi-app setups sharing one R2 bucket)
 *
 * @example
 * ```bash
 * # .env
 * APP_NAME=myapp        # optional, used as prefix
 * R2_BUCKET_NAME=storage
 * ```
 *
 * @example
 * ```toml
 * # wrangler.toml - automatically generated by alepha build
 * [[r2_buckets]]
 * binding = "R2"
 * bucket_name = "storage"
 * ```
 *
 * @example
 * ```ts
 * // Containers come from `$storage` (alepha/api/files)
 * class Media {
 *   avatars = $storage({ maxSize: 5, mimeTypes: ["image/png"] });
 *   documents = $storage({ maxSize: 50, mimeTypes: ["application/pdf"] });
 * }
 *
 * // Files stored at: myapp/avatars/uuid.png, myapp/documents/uuid.pdf
 * ```
 */
export class R2FileStorageProvider implements FileStorageProvider {
  protected readonly chunker = new MultipartChunker();

  protected readonly alepha = $inject(Alepha);
  protected readonly log = $logger();
  protected readonly crypto = $inject(CryptoProvider);
  protected readonly fileDetector = $inject(FileDetector);
  protected readonly env = $env(
    z.object({
      /**
       * The actual R2 bucket name in Cloudflare.
       */
      R2_BUCKET_NAME: z.string().describe("R2 bucket name in Cloudflare"),
    }),
  );

  protected r2?: R2Bucket;

  /**
   * Get the R2 bucket name from environment.
   */
  public get bucketName(): string {
    return this.env.R2_BUCKET_NAME;
  }

  /**
   * Get the optional prefix from APP_NAME environment variable.
   * Used for multi-app setups sharing the same R2 bucket.
   */
  public get prefix(): string | undefined {
    return this.alepha.env.APP_NAME;
  }

  protected readonly onStart = $hook({
    on: "start",
    handler: async () => {
      const cloudflareEnv = this.alepha.get("cloudflare.env") as
        | Record<string, unknown>
        | undefined;
      if (!cloudflareEnv) {
        throw new AlephaError(
          "Cloudflare Workers environment not found in Alepha store under 'cloudflare.env'.",
        );
      }

      const binding = cloudflareEnv[this.bucketName] as R2Bucket | undefined;
      if (!binding) {
        throw new AlephaError(
          `R2 binding '${this.bucketName}' not found in Cloudflare Workers environment.`,
        );
      }

      this.r2 = binding;

      const prefixStr = this.prefix ? `${this.prefix}/` : "";
      this.log.info(
        `R2 storage ready (bucket: ${this.bucketName}, prefix: ${prefixStr || "(none)"})`,
      );
    },
  });

  public async upload(
    bucketName: string,
    file: FileLike,
    fileId?: string,
  ): Promise<string> {
    const r2 = this.getR2();
    fileId ??= this.createId(file.type);
    const key = this.key(bucketName, fileId);

    this.log.trace(`Uploading '${key}'`);

    const metadata = {
      httpMetadata: { contentType: file.type },
      customMetadata: { originalName: file.name, bucket: bucketName },
    };

    if (file.size > 0) {
      await r2.put(key, await file.arrayBuffer(), metadata);
      return fileId;
    }

    // Length unknown — or zero, which is indistinguishable from unknown once a
    // `FileLike` comes off a stream. So the shape is decided by reading rather
    // than by asking: take the first part, and escalate to multipart only if a
    // second one exists.
    //
    // Multipart is not the default because `put()` is one request against
    // three, and because R2 refuses to complete an upload of a single short
    // part. It is the fallback because `put()` refuses a stream it cannot
    // measure — its type signature accepts one, which is how this compiled and
    // failed only on workerd: "Provided readable stream must have a known
    // length". Buffering to learn that length is not an option either, on a
    // runtime capped near 128 MB.
    const parts = this.chunker.parts(file)[Symbol.asyncIterator]();
    const first = await parts.next();
    const head = first.done ? new Uint8Array(0) : first.value;
    const second = await parts.next();

    if (second.done) {
      await r2.put(key, head as never, metadata);
      return fileId;
    }

    const upload = await r2.createMultipartUpload(key, metadata);
    const uploaded: R2UploadedPart[] = [];

    try {
      uploaded.push(await upload.uploadPart(1, head));
      uploaded.push(await upload.uploadPart(2, second.value));
      let partNumber = 3;
      while (true) {
        const next = await parts.next();
        if (next.done) {
          break;
        }
        uploaded.push(await upload.uploadPart(partNumber, next.value));
        partNumber++;
      }
      await upload.complete(uploaded);
    } catch (error) {
      await upload.abort().catch((abortError) => {
        // Reported, never swallowed: the upload has already failed, and losing
        // why the cleanup failed too is how orphaned parts become storage
        // nobody can account for.
        this.log.error(
          `Failed to abort multipart upload for '${key}'`,
          abortError,
        );
      });
      throw error;
    }

    return fileId;
  }

  public async download(bucketName: string, fileId: string): Promise<FileLike> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Downloading '${key}'`);

    const object = await r2.get(key);
    if (!object) {
      throw new FileNotFoundError(
        `File '${fileId}' not found in bucket '${bucketName}'.`,
      );
    }

    const originalName = object.customMetadata?.originalName ?? fileId;
    // An empty content-type is as useless as a missing one, and R2 stores
    // whatever it was given — so treat both as unknown.
    const contentType =
      object.httpMetadata?.contentType || "application/octet-stream";

    // R2 gives back a SINGLE-USE body: `body`, `arrayBuffer()` and `text()`
    // all drain the same object, so the returned FileLike could be read once
    // and only once — while Memory and Local serve repeat reads happily.
    // Materialise once and serve every accessor from that buffer, so the
    // backend no longer changes the contract. The upload path already buffers
    // (`file.arrayBuffer()`), so this keeps the provider internally consistent.
    const bytes = new Uint8Array(await object.arrayBuffer());

    return {
      name: originalName,
      type: contentType,
      size: object.size,
      lastModified: object.uploaded.getTime(),
      stream: () =>
        new ReadableStream({
          start(controller) {
            controller.enqueue(bytes);
            controller.close();
          },
        }) as unknown as ReadableStream,
      arrayBuffer: async () =>
        bytes.buffer.slice(
          bytes.byteOffset,
          bytes.byteOffset + bytes.byteLength,
        ) as ArrayBuffer,
      text: async () => new TextDecoder().decode(bytes),
    };
  }

  public async exists(bucketName: string, fileId: string): Promise<boolean> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Checking '${key}'`);

    const object = await r2.head(key);
    return object !== null;
  }

  public async delete(bucketName: string, fileId: string): Promise<void> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Deleting '${key}'`);

    // R2's delete doesn't throw if the file doesn't exist,
    // so we check existence first for consistency with other providers
    const exists = await this.exists(bucketName, fileId);
    if (!exists) {
      throw new FileNotFoundError(
        `File '${fileId}' not found in bucket '${bucketName}'.`,
      );
    }

    await r2.delete(key);
  }

  public async deleteMany(
    bucketName: string,
    fileIds: string[],
  ): Promise<void> {
    if (fileIds.length === 0) return;
    const r2 = this.getR2();
    const keys = fileIds.map((id) => this.key(bucketName, id));
    this.log.trace(`Deleting ${keys.length} keys from '${bucketName}'`);
    // R2 binding accepts a string[] and silently ignores missing keys.
    // Chunk at 1000 to stay within the documented batch limit.
    for (let i = 0; i < keys.length; i += 1000) {
      await r2.delete(keys.slice(i, i + 1000));
    }
  }

  public async list(bucketName: string): Promise<string[]> {
    const r2 = this.getR2();
    const keyPrefix = this.key(bucketName, "");
    this.log.trace(`Listing files in '${keyPrefix}'`);
    // Flat, single-page listing (~1000 keys). Not a search API.
    const listed = await r2.list({ prefix: keyPrefix });
    return listed.objects.map((object) => object.key.slice(keyPrefix.length));
  }

  /**
   * Build the full R2 key: {prefix}/{tenantId}/{bucketName}/{fileId}
   *
   * When a tenant is active on the current request/job (`currentTenantAtom`),
   * its id is inserted as a directory so a pooled multi-tenant worker keeps
   * each tenant's objects isolated. No tenant → the historical
   * `{prefix}/{bucketName}/{fileId}` layout is unchanged.
   */
  protected key(bucketName: string, fileId: string): string {
    const parts = [bucketName, fileId];
    const tenantId = this.alepha.store.get(currentTenantAtom)?.id;
    if (tenantId) {
      parts.unshift(tenantId);
    }
    if (this.prefix) {
      parts.unshift(this.prefix);
    }
    return parts.join("/");
  }

  protected getR2(): R2Bucket {
    if (!this.r2) {
      throw new AlephaError("R2 storage not initialized. Call start() first.");
    }
    return this.r2;
  }

  /**
   * MIME-derived, matching S3 and Local.
   *
   * It used to take everything after the last `.` of the user-controlled
   * FILENAME, so `"x.png/../y"` produced the extension `"png/../y"` — an
   * attacker-shaped, nested key (contained within the bucket prefix, but
   * still not what anyone intended). Two backends also disagreed on the id
   * scheme for the same upload.
   */
  protected createId(mimeType: string): string {
    const ext = this.fileDetector.getExtensionFromMimeType(mimeType);
    const id = this.crypto.randomUUID();
    return ext ? `${id}.${ext}` : id;
  }
}
