import { $hook, $inject, Alepha, AlephaError } from "alepha";
import { $logger } from "alepha/logger";
import type { CachePrimitive } from "../primitives/$cache.ts";
import { CacheProvider } from "./CacheProvider.ts";

// ---------------------------------------------------------------------------------------------------------------------

/**
 * KVNamespace interface matching Cloudflare's KV API.
 */
export interface KVNamespace {
  get(key: string, type: "arrayBuffer"): Promise<ArrayBuffer | null>;
  get(key: string, type: "text"): Promise<string | null>;
  get(key: string, type?: "text"): Promise<string | null>;
  put(
    key: string,
    value: string | ArrayBuffer | ReadableStream,
    options?: KVPutOptions,
  ): Promise<void>;
  delete(key: string): Promise<void>;
  list(options?: KVListOptions): Promise<KVListResult>;
}

export interface KVPutOptions {
  expiration?: number;
  expirationTtl?: number;
  metadata?: unknown;
}

export interface KVListOptions {
  prefix?: string;
  limit?: number;
  cursor?: string;
}

export interface KVListResult {
  keys: KVListKey[];
  list_complete: boolean;
  cursor?: string;
}

export interface KVListKey {
  name: string;
  expiration?: number;
  metadata?: unknown;
}

// ---------------------------------------------------------------------------------------------------------------------

/**
 * Default KV binding name used in wrangler configuration.
 */
export const KV_DEFAULT_BINDING = "KV_CACHE";

/**
 * Cloudflare KV refuses an `expirationTtl` below 60 seconds.
 */
export const KV_MIN_EXPIRATION_TTL = 60;

// ---------------------------------------------------------------------------------------------------------------------

/**
 * Cloudflare KV cache provider.
 *
 * Uses a KV namespace binding for all cache operations.
 * Keys are stored as: `cache:{name}:{key}`
 *
 * **Required Cloudflare binding:**
 * - `KV_CACHE` - A KV namespace binding in wrangler configuration
 *
 * @example
 * ```toml
 * # wrangler.toml - automatically generated by alepha build
 * [[kv_namespaces]]
 * binding = "KV_CACHE"
 * id = "abc123"
 * ```
 */
export class CloudflareKVProvider extends CacheProvider {
  protected readonly alepha = $inject(Alepha);
  protected readonly log = $logger();

  protected kv?: KVNamespace;

  /**
   * Cache names already warned about, so a hot cache does not repeat the
   * clamp warning on every write. The clamp is a static consequence of
   * configuration — saying it once is saying it.
   */
  protected readonly warnedClamps = new Set<string>();

  protected readonly onStart = $hook({
    on: "start",
    handler: async () => {
      const caches = this.alepha
        .primitives<CachePrimitive>("cache")
        .filter((it) => it.provider === this);

      if (caches.length === 0) {
        this.log.info(
          "CloudflareKVProvider is registered but no cache primitives are using it. Skipping KV initialization.",
        );
        return;
      }

      const cloudflareEnv = this.alepha.get("cloudflare.env") as
        | Record<string, unknown>
        | undefined;
      if (!cloudflareEnv) {
        throw new AlephaError(
          "Cloudflare Workers environment not found in Alepha store under 'cloudflare.env'.",
        );
      }

      const binding = cloudflareEnv[KV_DEFAULT_BINDING] as
        | KVNamespace
        | undefined;
      if (!binding) {
        throw new AlephaError(
          `KV binding '${KV_DEFAULT_BINDING}' not found in Cloudflare Workers environment.`,
        );
      }

      this.kv = binding;

      this.log.info("Cloudflare KV cache OK");
    },
  });

  public async get(name: string, key: string): Promise<Uint8Array | undefined> {
    if (!this.alepha.isStarted()) {
      return;
    }

    const kvKey = this.prefix(name, key);
    const buffer = await this.getKV().get(kvKey, "arrayBuffer");
    if (!buffer) {
      return;
    }

    this.log.debug("Cache hit", {
      size: buffer.byteLength,
      key: kvKey,
    });

    return new Uint8Array(buffer);
  }

  public async set(
    name: string,
    key: string,
    value: Uint8Array,
    ttl?: number,
  ): Promise<Uint8Array> {
    if (!this.alepha.isReady()) {
      return new Uint8Array(value);
    }

    const kvKey = this.prefix(name, key);
    const options: KVPutOptions = {};

    if (ttl) {
      options.expirationTtl = this.expirationTtl(ttl, name);
    }

    await this.getKV().put(
      kvKey,
      value.buffer.slice(
        value.byteOffset,
        value.byteOffset + value.byteLength,
      ) as ArrayBuffer,
      options,
    );
    return value;
  }

  public async del(name: string, ...keys: string[]): Promise<void> {
    const kv = this.getKV();

    if (keys.length === 0) {
      // Delete all keys under this cache name
      const prefix = this.prefix(name);
      const allKeys = await this.listAllKeys(`${prefix}:`);
      for (const k of allKeys) {
        await kv.delete(k);
      }
      return;
    }

    const nameKey = this.prefix(name);
    for (const key of keys) {
      const fullKey = key.startsWith(nameKey) ? key : this.prefix(name, key);
      await kv.delete(fullKey);
    }
  }

  public async has(name: string, key: string): Promise<boolean> {
    const kvKey = this.prefix(name, key);
    const value = await this.getKV().get(kvKey, "text");
    return value !== null;
  }

  public async keys(name: string, filter?: string): Promise<string[]> {
    const prefix = filter
      ? `${this.prefix(name)}:${filter}`
      : `${this.prefix(name)}:`;

    return this.listAllKeys(prefix);
  }

  public async clear(): Promise<void> {
    this.log.debug("Clearing all cache");
    const kv = this.getKV();
    const allKeys = await this.listAllKeys("cache:");
    for (const key of allKeys) {
      await kv.delete(key);
    }
  }

  /**
   * **Not atomic.** KV has no INCR: this reads, adds, and writes back, so two
   * isolates incrementing concurrently can lose an update. Fine for cache
   * statistics and best-effort counters; NOT sufficient on its own for a rate
   * limiter that must never over-admit — route that through a Durable Object,
   * or accept that the ceiling is approximate under concurrency.
   *
   * Redis and Postgres implement this atomically; only KV cannot.
   */
  public async incr(
    name: string,
    key: string,
    amount: number,
    ttl?: number,
  ): Promise<number> {
    const kvKey = this.prefix(name, key);
    const kv = this.getKV();

    const existing = await kv.get(kvKey, "text");
    let current = 0;

    if (existing !== null) {
      current = Number.parseInt(existing, 10) || 0;
    }

    const newValue = current + amount;
    // NOTE: sliding here (each put resets the TTL) — KV cannot express "keep
    // the original expiry" without another read.
    await kv.put(
      kvKey,
      String(newValue),
      ttl ? { expirationTtl: this.expirationTtl(ttl, name) } : undefined,
    );
    return newValue;
  }

  /**
   * Convert a millisecond TTL to KV's `expirationTtl` (seconds), applying
   * KV's own 60-second floor.
   *
   * The clamp is not optional — KV rejects anything shorter — but it used to
   * be invisible: a `$cache({ ttl: [5, "seconds"] })` deployed to Workers
   * served entries up to twelve times staler than configured, with nothing
   * anywhere saying so, and the same code on any other provider honoured the
   * 5 seconds exactly. Warning once per cache makes the divergence
   * discoverable at the only moment it can be acted on.
   */
  protected expirationTtl(ttlMs: number, name: string): number {
    const requested = Math.ceil(ttlMs / 1000);
    if (requested >= KV_MIN_EXPIRATION_TTL) {
      return requested;
    }

    if (!this.warnedClamps.has(name)) {
      this.warnedClamps.add(name);
      this.log.warn(
        `Cache '${name}' asks for a ${requested}s TTL, but Cloudflare KV enforces a ` +
          `${KV_MIN_EXPIRATION_TTL}s minimum — entries will live up to ${KV_MIN_EXPIRATION_TTL}s. ` +
          "Use a shorter-lived tier (the in-memory L1) if the freshness matters.",
      );
    }

    return KV_MIN_EXPIRATION_TTL;
  }

  /**
   * Build the full KV key: `cache:{name}:{key}`
   */
  protected prefix(...path: string[]): string {
    return ["cache", ...path].join(":");
  }

  protected getKV(): KVNamespace {
    if (!this.kv) {
      throw new AlephaError(
        "KV namespace not initialized. Call start() first.",
      );
    }
    return this.kv;
  }

  /**
   * List all keys matching a prefix, handling pagination.
   */
  protected async listAllKeys(prefix: string): Promise<string[]> {
    const kv = this.getKV();
    const allKeys: string[] = [];
    let cursor: string | undefined;

    do {
      const result = await kv.list({
        prefix,
        cursor,
      });

      for (const key of result.keys) {
        allKeys.push(key.name);
      }

      cursor = result.list_complete ? undefined : result.cursor;
    } while (cursor);

    return allKeys;
  }
}
