/**
 * Sombregué — six islands of an archipelago the goblin warband is taking one shore at a time.
 *
 * Every map is generated by `terrain.ts` from the pack's own assets and the engine's own brushes, so
 * the shorelines are irregular, the plateaus carry real cliff faces, and the trees crowd the coast
 * the way Tiny Swords' promo art does.
 *
 * There are no `exit` events and no adventure graph here: every crossing is a `teleport` command on
 * an ordinary scripted event, which is the one mechanism an author can open and retarget. Because a
 * teleport needs its destination map's uuid and the server mints those, the pages that carry one are
 * built LAZILY — `linkedEvents(ids)` is called by the seeder once every map exists.
 */

import type { EventCommand } from "@lindocara/engine/event-commands.js";
import type { MonsterSpecies } from "@lindocara/engine/game.js";
import { elementCoversCell, elementFitsMap, type MapElement } from "@lindocara/engine/map-data.js";
import {
  defaultEventPage,
  functionalEvent,
  type MapEvent,
  type MapEventPage,
} from "@lindocara/engine/map-events.js";
import { encodeTileLayer, type TileLayer } from "@lindocara/engine/tile-layer-codec.js";
import type { EditorAssetId } from "@lindocara/engine/tiny-swords-catalog.js";

import {
  BUSHES,
  blob,
  carveStairs,
  causeway,
  countCells,
  element,
  emptyMask,
  inland,
  type Mask,
  maskAt,
  offshoreRocks,
  paintGround,
  placeableMask,
  ROCKS,
  raise,
  rectMask,
  reserve,
  rngFor,
  STUMPS,
  scatter,
  shoreTreeLine,
  smooth,
  snapper,
} from "../../lib/island-terrain.js";

export type MapKey = "port" | "greve" | "bois" | "enclos" | "camp" | "eperon";

export interface MapContent {
  key: MapKey;
  name: string;
  cols: number;
  rows: number;
  layers: string[];
  elements: MapElement[];
  spawn: { col: number; row: number };
  /** Events with no cross-map reference — placed in pass one. */
  events: MapEvent[];
  /** Events carrying a `teleport`, resolved once every map id is known. */
  linkedEvents(ids: Record<MapKey, string>): MapEvent[];
}

export interface WorldRefs {
  /** Quest givers and turn-in targets, by stable name. */
  npc: Record<string, MapEvent>;
  /** The warchief, for the boss objective. */
  grumlok: MapEvent;
  /** Supply crates the "recover the stores" objective counts. */
  crates: MapEvent[];
}

/** Every id below is verified against `EVENT_GRAPHIC_ASSETS`; nothing here is invented. */
const KNIGHT = {
  captain: "character.units-blue-units-warrior.warrior-idle" as EditorAssetId,
  monk: "character.units-blue-units-monk.idle" as EditorAssetId,
  merchant: "character.units-yellow-units-pawn.pawn-idle-gold" as EditorAssetId,
  scout: "character.units-purple-units-archer.archer-idle" as EditorAssetId,
};

const CRATE = "decoration.deco.09" as EditorAssetId;
const GOBLIN_HOUSE = "building.factions-goblins-buildings-wood-house.goblin-house" as EditorAssetId;
const GOBLIN_TOWER =
  "building.factions-goblins-buildings-wood-tower.wood-tower-inconstruction" as EditorAssetId;
const HOUSE = "building.buildings-blue-buildings.house1" as EditorAssetId;
const HOUSE2 = "building.buildings-blue-buildings.house2" as EditorAssetId;
const CASTLE = "building.buildings-blue-buildings.castle" as EditorAssetId;
const TOWER = "building.buildings-blue-buildings.tower" as EditorAssetId;

export const SWITCH_GRUMLOK = "0001";
export const AREA_CAMP = "camp_grumlok";
export const ITEM_CRATE = "health_potion";

let ordinal = 0;
function nextOrdinal(): number {
  ordinal += 1;
  return ordinal;
}

function say(name: string, text: string): EventCommand {
  return { t: "say", name, text };
}

function page(overrides: Partial<MapEventPage>): MapEventPage {
  return { ...defaultEventPage(), ...overrides };
}

function npc(params: {
  col: number;
  row: number;
  name: string;
  graphic: EditorAssetId;
  lines: EventCommand[][];
}): MapEvent {
  return {
    id: crypto.randomUUID(),
    col: params.col,
    row: params.row,
    name: params.name,
    ordinal: nextOrdinal(),
    kind: "normal",
    species: null,
    patrolRadius: null,
    pages: params.lines.map((commands) =>
      page({ graphicAssetId: params.graphic, trigger: "action", commands }),
    ),
  };
}

function monster(
  col: number,
  row: number,
  species: MonsterSpecies,
  name: string,
  patrolRadius = 96,
): MapEvent {
  return functionalEvent({
    id: crypto.randomUUID(),
    col,
    row,
    ordinal: nextOrdinal(),
    kind: "monster",
    species,
    patrolRadius,
    name,
  });
}

/** A crossing: step on it and the teleport command carries you to another island. */
function ferry(params: {
  col: number;
  row: number;
  name: string;
  to: MapKey;
  dest: { col: number; row: number };
  ids: Record<MapKey, string>;
}): MapEvent {
  return {
    id: crypto.randomUUID(),
    col: params.col,
    row: params.row,
    name: params.name,
    ordinal: nextOrdinal(),
    kind: "normal",
    species: null,
    patrolRadius: null,
    pages: [
      page({
        trigger: "player-touch",
        commands: [
          {
            t: "teleport",
            mapId: params.ids[params.to],
            col: params.dest.col,
            row: params.dest.row,
          },
        ],
      }),
    ],
  };
}

/** A supply crate: one-shot, guarded by its own self-switch, exactly as an author would build it. */
function crate(col: number, row: number, name: string): MapEvent {
  return {
    id: crypto.randomUUID(),
    col,
    row,
    name,
    ordinal: nextOrdinal(),
    kind: "normal",
    species: null,
    patrolRadius: null,
    pages: [
      page({
        graphicAssetId: CRATE,
        trigger: "action",
        commands: [
          say("", "Une caisse de vivres marquée du sceau d’Aubépine. Vous la récupérez."),
          { t: "changeItems", itemId: ITEM_CRATE, count: 1 },
          { t: "setSelfSwitch", selfSwitch: "A", value: true },
        ],
      }),
      page({
        graphicAssetId: CRATE,
        condSelfSwitch: "A",
        trigger: "action",
        commands: [say("", "La caisse est vide.")],
      }),
    ],
  };
}

interface Built<K extends string> {
  cols: number;
  rows: number;
  land: Mask;
  layers: TileLayer[];
  elements: MapElement[];
  /** The requested anchors, snapped onto cells that actually exist on the generated island. */
  at: Record<K, { col: number; row: number }>;
}

/** Terrain + a first composition pass, shared by every island. */
function island<K extends string>(params: {
  seed: string;
  cols: number;
  rows: number;
  shape(land: Mask, rng: ReturnType<typeof rngFor>): void;
  plateau?(plateau: Mask, rng: ReturnType<typeof rngFor>): void;
  /** Wished-for positions by name. Each is snapped to the nearest legal cell and reserved. */
  anchors: Record<K, { col: number; row: number }>;
  treeDensity?: number;
  bushDensity?: number;
}): Built<K> {
  const rng = rngFor(params.seed);
  const land = emptyMask(params.cols, params.rows);
  params.shape(land, rng);
  smooth(land, 2);

  let layers = paintGround(params.cols, params.rows, land);
  let plateauMask: Mask | null = null;
  if (params.plateau) {
    const plateau = emptyMask(params.cols, params.rows);
    params.plateau(plateau, rng);
    // A plateau may only sit on land, or its cliff face would rise out of the sea.
    for (const [row, line] of plateau.entries()) {
      for (const [col, filled] of line.entries()) {
        if (filled && !maskAt(land, col, row)) line[col] = false;
      }
    }
    layers = raise(layers, plateau, 1);
    // A terrace nobody can climb is scenery, not level design.
    const stairs = carveStairs(layers, plateau, land);
    layers = stairs.layers;
    plateauMask = plateau;
  }

  // Every hand-written coordinate is a WISH; the snapper turns it into a legal cell on the terrain
  // that was actually generated, and reserves it so two events never share a tile.
  const snap = snapper(placeableMask(land, plateauMask));
  const at = {} as Record<K, { col: number; row: number }>;
  for (const name of Object.keys(params.anchors) as K[]) {
    const wish = params.anchors[name];
    at[name] = snap.at(wish.col, wish.row);
  }
  const reserved = reserve(Object.values<{ col: number; row: number }>(at), 1);
  const interior = inland(land, 2);
  // A prop occupies a FOOTPRINT, not a cell: a tree's canopy reaches several rows above its trunk, so
  // one planted near the top edge hangs off the map and the wire parser rejects the whole map. Asking
  // the engine's own `elementFitsMap` is exact for every asset, where a hand-guessed margin is not.
  const composed = [
    ...shoreTreeLine(land, rng, reserved, params.treeDensity ?? 0.4),
    ...scatter(interior, rng, reserved, BUSHES, params.bushDensity ?? 0.07),
    ...scatter(interior, rng, reserved, ROCKS, 0.025),
    ...offshoreRocks(params.cols, params.rows, land, rng, 0.06),
  ]
    .filter((candidate) => elementFitsMap(candidate, params.cols, params.rows))
    // Reserving a cell stops a prop being PLACED there; it does not stop a neighbour's canopy
    // reaching over it. The server rejects a spawn covered by scenery and an event on solid ground,
    // so drop anything whose FOOTPRINT lands on an anchor — the same `elementCoversCell` it uses.
    .filter(
      (candidate) =>
        !Object.values<{ col: number; row: number }>(at).some((anchor) =>
          elementCoversCell(candidate, anchor.col, anchor.row),
        ),
    );
  // Two scatter passes over the same interior can land on the same cell AND roll the same quarter-cell
  // offset. That slot is the D1 primary key, so the server refuses the save; decorations may stack,
  // but not in the identical slot. Keep the first, drop the collision.
  const slots = new Set<string>();
  const elements = composed.filter((candidate) => {
    const slot = `${candidate.col}:${candidate.row}:${candidate.offsetX}:${candidate.offsetY}`;
    if (slots.has(slot)) return false;
    slots.add(slot);
    return true;
  });
  return {
    cols: params.cols,
    rows: params.rows,
    land,
    layers,
    elements,
    at,
  };
}

function encode(layers: TileLayer[]): string[] {
  return layers.map(encodeTileLayer);
}

export interface BuiltWorld {
  maps: MapContent[];
  refs: WorldRefs;
}

export function buildSombregue(): BuiltWorld {
  ordinal = 0;

  // ── ① Port-Aubépine — the hub. A castle isle joined to a village isle by an isthmus.
  const portSpawn = { col: 16, row: 15 };
  const portCaptain = { col: 20, row: 14 };
  const portMonk = { col: 13, row: 12 };
  const portMerchant = { col: 18, row: 18 };
  const portFerry = { col: 40, row: 16 };
  const port = island({
    seed: "port-aubepine",
    cols: 46,
    rows: 30,
    shape: (land, rng) => {
      blob(land, rng, { col: 15, row: 14, radiusX: 12, radiusY: 9, wobble: 0.28 });
      blob(land, rng, { col: 34, row: 17, radiusX: 9, radiusY: 7, wobble: 0.3 });
      causeway(land, { col: 24, row: 15 }, { col: 29, row: 16 }, 1);
    },
    plateau: (plateau) => rectMask(plateau, 10, 8, 17, 12),
    anchors: {
      spawn: portSpawn,
      captain: portCaptain,
      monk: portMonk,
      merchant: portMerchant,
      ferry: portFerry,
    },
    treeDensity: 0.34,
  });
  port.elements.push(
    element(CASTLE, 12, 10),
    element(TOWER, 18, 9),
    element(HOUSE, 20, 17),
    element(HOUSE2, 23, 19),
    element(HOUSE, 12, 18),
    element(TOWER, 33, 15),
  );

  const capitaine = npc({
    ...port.at.captain,
    name: "Capitaine Vaudray",
    graphic: KNIGHT.captain,
    lines: [
      [
        say(
          "Capitaine Vaudray",
          "Sombregué perd une grève par semaine. Les gobelins débarquent, pillent, repartent. Aide-nous.",
        ),
      ],
      [say("Capitaine Vaudray", "Grumlok est tombé. L’archipel respire — grâce à toi.")],
    ],
  });
  const frereOsmond = npc({
    ...port.at.monk,
    name: "Frère Osmond",
    graphic: KNIGHT.monk,
    lines: [
      [
        say(
          "Frère Osmond",
          "Nos caisses de vivres sont sur la Grève aux Épaves, éventrées par les pillards. Rapporte ce qui reste.",
        ),
      ],
    ],
  });
  const marchand = npc({
    ...port.at.merchant,
    name: "Perrine la Colporteuse",
    graphic: KNIGHT.merchant,
    lines: [
      [
        say("Perrine", "Fioles, élixirs — tout ce qu’il faut pour ne pas finir dans une marmite."),
        { t: "openShop" },
      ],
    ],
  });

  // ── ② La Grève aux Épaves — first blood: spear goblins among the wrecks.
  const greveArrive = { col: 6, row: 14 };
  const greveBack = { col: 3, row: 14 };
  const greveOn = { col: 34, row: 12 };
  const greve = island({
    seed: "greve-aux-epaves",
    cols: 40,
    rows: 26,
    shape: (land, rng) => {
      blob(land, rng, { col: 18, row: 13, radiusX: 15, radiusY: 9, wobble: 0.34 });
      blob(land, rng, { col: 33, row: 11, radiusX: 6, radiusY: 5, wobble: 0.3 });
    },
    anchors: {
      arrive: greveArrive,
      back: greveBack,
      on: greveOn,
      crate1: { col: 11, row: 11 },
      crate2: { col: 20, row: 17 },
      crate3: { col: 29, row: 10 },
      m1: { col: 13, row: 13 },
      m2: { col: 18, row: 10 },
      m3: { col: 21, row: 15 },
      m4: { col: 26, row: 12 },
      m5: { col: 30, row: 14 },
    },
    treeDensity: 0.26,
    bushDensity: 0.05,
  });
  greve.elements.push(
    element(STUMPS[0] as EditorAssetId, 14, 16),
    element(STUMPS[2] as EditorAssetId, 22, 9),
  );
  const crates = (["crate1", "crate2", "crate3"] as const).map((key) =>
    crate(greve.at[key].col, greve.at[key].row, "Caisse de vivres"),
  );
  const greveMonsters = (["m1", "m2", "m3", "m4", "m5"] as const).map((key) =>
    monster(greve.at[key].col, greve.at[key].row, "spear_goblin", "Pillard", 96),
  );

  // ── ③ Le Bois de Ronceleau — torch goblins under a closed canopy.
  const boisArrive = { col: 5, row: 12 };
  const boisBack = { col: 2, row: 12 };
  const boisOn = { col: 30, row: 20 };
  const bois = island({
    seed: "bois-de-ronceleau",
    cols: 36,
    rows: 26,
    shape: (land, rng) => {
      blob(land, rng, { col: 17, row: 13, radiusX: 14, radiusY: 10, wobble: 0.3 });
    },
    plateau: (plateau) => rectMask(plateau, 20, 6, 28, 11),
    anchors: {
      arrive: boisArrive,
      back: boisBack,
      on: boisOn,
      wynn: { col: 8, row: 14 },
      m1: { col: 12, row: 10 },
      m2: { col: 16, row: 16 },
      m3: { col: 22, row: 14 },
      m4: { col: 26, row: 17 },
      m5: { col: 19, row: 9 },
    },
    treeDensity: 0.55,
    bushDensity: 0.16,
  });
  const boisMonsters = [
    ...(["m1", "m2", "m3", "m4"] as const).map((key) =>
      monster(bois.at[key].col, bois.at[key].row, "torch_goblin", "Incendiaire", 112),
    ),
    monster(bois.at.m5.col, bois.at.m5.row, "spear_goblin", "Guetteur", 80),
  ];
  const eclaireuse = npc({
    ...bois.at.wynn,
    name: "Éclaireuse Wynn",
    graphic: KNIGHT.scout,
    lines: [
      [
        say(
          "Éclaireuse Wynn",
          "Ils élèvent des sangliers dans les enclos, à l’est. C’est de là que sortent leurs cavaliers.",
        ),
      ],
    ],
  });

  // ── ④ Les Enclos — the drove: war pigs, then the riders they carry.
  const enclosArrive = { col: 5, row: 13 };
  const enclosBack = { col: 2, row: 13 };
  const enclosOn = { col: 32, row: 8 };
  const enclos = island({
    seed: "les-enclos",
    cols: 38,
    rows: 24,
    shape: (land, rng) => {
      blob(land, rng, { col: 16, row: 12, radiusX: 13, radiusY: 9, wobble: 0.26 });
      blob(land, rng, { col: 31, row: 9, radiusX: 6, radiusY: 5, wobble: 0.3 });
      causeway(land, { col: 25, row: 11 }, { col: 28, row: 10 }, 1);
    },
    anchors: {
      arrive: enclosArrive,
      back: enclosBack,
      on: enclosOn,
      p1: { col: 11, row: 11 },
      p2: { col: 14, row: 14 },
      p3: { col: 18, row: 10 },
      p4: { col: 21, row: 15 },
      r1: { col: 16, row: 17 },
      r2: { col: 24, row: 12 },
      r3: { col: 29, row: 9 },
      hut1: { col: 14, row: 19 },
      hut2: { col: 20, row: 7 },
    },
    treeDensity: 0.2,
    bushDensity: 0.05,
  });
  enclos.elements.push(
    element(GOBLIN_HOUSE, enclos.at.hut1.col, enclos.at.hut1.row),
    element(GOBLIN_HOUSE, enclos.at.hut2.col, enclos.at.hut2.row),
  );
  const enclosMonsters = [
    ...(["p1", "p2", "p3", "p4"] as const).map((key) =>
      monster(enclos.at[key].col, enclos.at[key].row, "war_pig", "Sanglier", 128),
    ),
    ...(["r1", "r2", "r3"] as const).map((key) =>
      monster(enclos.at[key].col, enclos.at[key].row, "pig_rider", "Chevaucheur", 144),
    ),
  ];

  // ── ⑤ Le Camp de Grumlok — towers, huts and the shaman who wards them.
  const campArrive = { col: 5, row: 15 };
  const campBack = { col: 2, row: 15 };
  const campOn = { col: 33, row: 10 };
  const camp = island({
    seed: "camp-de-grumlok",
    cols: 40,
    rows: 28,
    shape: (land, rng) => {
      blob(land, rng, { col: 18, row: 15, radiusX: 15, radiusY: 11, wobble: 0.24 });
      blob(land, rng, { col: 33, row: 11, radiusX: 6, radiusY: 6, wobble: 0.3 });
      causeway(land, { col: 27, row: 13 }, { col: 30, row: 12 }, 1);
    },
    plateau: (plateau) => rectMask(plateau, 14, 8, 24, 13),
    anchors: {
      arrive: campArrive,
      back: campBack,
      on: campOn,
      threshold: { col: 12, row: 15 },
      s1: { col: 15, row: 14 },
      s2: { col: 23, row: 16 },
      s3: { col: 19, row: 19 },
      g1: { col: 17, row: 12 },
      g2: { col: 25, row: 13 },
      g3: { col: 21, row: 22 },
      tower1: { col: 12, row: 20 },
      tower2: { col: 26, row: 21 },
      hut1: { col: 16, row: 23 },
      hut2: { col: 22, row: 24 },
    },
    treeDensity: 0.3,
    bushDensity: 0.06,
  });
  camp.elements.push(
    element(GOBLIN_TOWER, camp.at.tower1.col, camp.at.tower1.row),
    element(GOBLIN_TOWER, camp.at.tower2.col, camp.at.tower2.row),
    element(GOBLIN_HOUSE, camp.at.hut1.col, camp.at.hut1.row),
    element(GOBLIN_HOUSE, camp.at.hut2.col, camp.at.hut2.row),
  );
  const campThreshold: MapEvent = {
    id: crypto.randomUUID(),
    col: camp.at.threshold.col,
    row: camp.at.threshold.row,
    name: "Lisière du camp",
    ordinal: nextOrdinal(),
    kind: "normal",
    species: null,
    patrolRadius: null,
    pages: [page({ trigger: "player-touch", commands: [{ t: "enterArea", areaId: AREA_CAMP }] })],
  };
  const campMonsters = [
    ...(["s1", "s2", "s3"] as const).map((key) =>
      monster(camp.at[key].col, camp.at[key].row, "hex_shaman", "Chamane", 112),
    ),
    monster(camp.at.g1.col, camp.at.g1.row, "spear_goblin", "Garde du camp", 96),
    monster(camp.at.g2.col, camp.at.g2.row, "torch_goblin", "Garde du camp", 96),
    monster(camp.at.g3.col, camp.at.g3.row, "pig_rider", "Chevaucheur d’élite", 144),
  ];

  // ── ⑥ L'Éperon — the warchief, alone on a cliff.
  const eperonArrive = { col: 5, row: 12 };
  const eperonBack = { col: 2, row: 12 };
  const eperon = island({
    seed: "l-eperon",
    cols: 30,
    rows: 22,
    shape: (land, rng) => {
      blob(land, rng, { col: 14, row: 11, radiusX: 11, radiusY: 8, wobble: 0.22 });
    },
    plateau: (plateau) => rectMask(plateau, 15, 7, 22, 14),
    anchors: {
      arrive: eperonArrive,
      back: eperonBack,
      wynn: { col: 7, row: 12 },
      grumlok: { col: 13, row: 11 },
      s1: { col: 9, row: 9 },
      r1: { col: 11, row: 15 },
      tower: { col: 10, row: 6 },
      hut: { col: 9, row: 17 },
    },
    treeDensity: 0.24,
    bushDensity: 0.04,
  });
  eperon.elements.push(
    element(GOBLIN_TOWER, eperon.at.tower.col, eperon.at.tower.row),
    element(GOBLIN_HOUSE, eperon.at.hut.col, eperon.at.hut.row),
  );
  const grumlok = monster(
    eperon.at.grumlok.col,
    eperon.at.grumlok.row,
    "minotaur_brute",
    "Grumlok, chef de guerre",
    176,
  );
  const eperonMonsters = [
    grumlok,
    monster(eperon.at.s1.col, eperon.at.s1.row, "hex_shaman", "Chamane lige", 96),
    monster(eperon.at.r1.col, eperon.at.r1.row, "pig_rider", "Garde du chef", 128),
  ];
  const wynnEperon = npc({
    ...eperon.at.wynn,
    name: "Éclaireuse Wynn",
    graphic: KNIGHT.scout,
    lines: [
      [say("Éclaireuse Wynn", "Grumlok est là-haut. Ne le laisse pas te charger de face.")],
      [
        say("Éclaireuse Wynn", "Le chef de guerre est tombé. Rentrons à Port-Aubépine."),
        {
          t: "choices",
          prompt: "Rentrer au port ?",
          options: [
            { label: "Oui, rentrons", body: [{ t: "endAdventure" }] },
            { label: "Pas encore", body: [say("Éclaireuse Wynn", "Je t’attends ici.")] },
          ],
        },
      ],
    ],
  });

  const maps: MapContent[] = [
    {
      key: "port",
      name: "Port-Aubépine",
      cols: port.cols,
      rows: port.rows,
      layers: encode(port.layers),
      elements: port.elements,
      spawn: port.at.spawn,
      events: [capitaine, frereOsmond, marchand],
      linkedEvents: (ids) => [
        ferry({
          ...port.at.ferry,
          name: "Vers la Grève aux Épaves",
          to: "greve",
          dest: greve.at.arrive,
          ids,
        }),
      ],
    },
    {
      key: "greve",
      name: "La Grève aux Épaves",
      cols: greve.cols,
      rows: greve.rows,
      layers: encode(greve.layers),
      elements: greve.elements,
      spawn: greve.at.arrive,
      events: [...crates, ...greveMonsters],
      linkedEvents: (ids) => [
        ferry({ ...greve.at.back, name: "Retour au port", to: "port", dest: port.at.spawn, ids }),
        ferry({
          ...greve.at.on,
          name: "Vers le Bois de Ronceleau",
          to: "bois",
          dest: bois.at.arrive,
          ids,
        }),
      ],
    },
    {
      key: "bois",
      name: "Le Bois de Ronceleau",
      cols: bois.cols,
      rows: bois.rows,
      layers: encode(bois.layers),
      elements: bois.elements,
      spawn: bois.at.arrive,
      events: [eclaireuse, ...boisMonsters],
      linkedEvents: (ids) => [
        ferry({
          ...bois.at.back,
          name: "Retour à la grève",
          to: "greve",
          dest: greve.at.arrive,
          ids,
        }),
        ferry({
          ...bois.at.on,
          name: "Vers les Enclos",
          to: "enclos",
          dest: enclos.at.arrive,
          ids,
        }),
      ],
    },
    {
      key: "enclos",
      name: "Les Enclos",
      cols: enclos.cols,
      rows: enclos.rows,
      layers: encode(enclos.layers),
      elements: enclos.elements,
      spawn: enclos.at.arrive,
      events: enclosMonsters,
      linkedEvents: (ids) => [
        ferry({ ...enclos.at.back, name: "Retour au bois", to: "bois", dest: bois.at.arrive, ids }),
        ferry({
          ...enclos.at.on,
          name: "Vers le camp de Grumlok",
          to: "camp",
          dest: camp.at.arrive,
          ids,
        }),
      ],
    },
    {
      key: "camp",
      name: "Le Camp de Grumlok",
      cols: camp.cols,
      rows: camp.rows,
      layers: encode(camp.layers),
      elements: camp.elements,
      spawn: camp.at.arrive,
      events: [campThreshold, ...campMonsters],
      linkedEvents: (ids) => [
        ferry({
          ...camp.at.back,
          name: "Retour aux enclos",
          to: "enclos",
          dest: enclos.at.arrive,
          ids,
        }),
        ferry({ ...camp.at.on, name: "Vers l’Éperon", to: "eperon", dest: eperon.at.arrive, ids }),
      ],
    },
    {
      key: "eperon",
      name: "L’Éperon",
      cols: eperon.cols,
      rows: eperon.rows,
      layers: encode(eperon.layers),
      elements: eperon.elements,
      spawn: eperon.at.arrive,
      events: [wynnEperon, ...eperonMonsters],
      linkedEvents: (ids) => [
        ferry({ ...eperon.at.back, name: "Retour au camp", to: "camp", dest: camp.at.arrive, ids }),
      ],
    },
  ];

  return {
    maps,
    refs: {
      npc: {
        capitaine,
        osmond: frereOsmond,
        wynn: eclaireuse,
        wynnEperon,
      },
      grumlok,
      crates,
    },
  };
}

/** How much of each island is walkable — a cheap sanity number the seeder prints. */
export function landCells(map: MapContent, built: Mask): number {
  return countCells(built) * (map.cols > 0 ? 1 : 1);
}
