import { execFileSync } from "node:child_process";
import { readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface MusicProfileSource {
  id: string;
  title: string;
  description: string;
  biomes: string[];
  moods: string[];
  instruments: string[];
  bpm: number;
  intensity: number;
  duration: number;
  loopable: boolean;
  transitionMs: number;
  fallbackTrackIds: string[];
  prompt: string;
}

interface MusicSource {
  schemaVersion: number;
  dna: Record<string, unknown>;
  mainMotif: Record<string, unknown>;
  generator: { captionLimit: number } & Record<string, unknown>;
  profiles: MusicProfileSource[];
}

interface GenerationSource {
  id: string;
  title: string;
  profile: string;
  biome: string[];
  mood: string[];
  intensity: number;
  bpm: number;
  duration: number;
  loopable: boolean;
  seed: number;
  generator: string;
  generationPrompt: string;
  generationParams: Record<string, unknown>;
  src: string;
  file: string;
  createdAt: string;
  regeneratedAt?: string;
}

interface GenerationRegistry {
  schemaVersion: number;
  generations: GenerationSource[];
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const configPath = path.join(root, "studio", "musics", "lindocara-music.json");
const registryPath = path.join(root, "studio", "musics", "generations.json");
const outputPath = path.join(root, "packages", "engine", "src", "music-catalog.generated.ts");

function fail(message: string): never {
  throw new Error(`[music-catalog] ${message}`);
}

function assertUnique(values: readonly string[], label: string): void {
  const seen = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) fail(`duplicate ${label}: ${value}`);
    seen.add(value);
  }
}

function serialise(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function formatTypeScript(source: string): string {
  const biome = path.join(root, "node_modules", "@biomejs", "biome", "bin", "biome");
  return execFileSync(process.execPath, [biome, "format", "--stdin-file-path", outputPath], {
    cwd: root,
    encoding: "utf8",
    input: source,
  });
}

async function main(): Promise<void> {
  const config = JSON.parse(await readFile(configPath, "utf8")) as MusicSource;
  const registry = JSON.parse(await readFile(registryPath, "utf8")) as GenerationRegistry;
  if (config.schemaVersion !== 1 || registry.schemaVersion !== 1)
    fail("unsupported schema version");
  assertUnique(
    config.profiles.map((item) => item.id),
    "profile id",
  );
  assertUnique(
    registry.generations.map((item) => item.id),
    "generation id",
  );
  const profileIds = new Set(config.profiles.map((item) => item.id));
  for (const item of config.profiles) {
    if (!/^[a-z][a-z0-9-]*$/.test(item.id)) fail(`invalid profile id: ${item.id}`);
    if (item.bpm < 30 || item.bpm > 300) fail(`profile ${item.id} has an invalid BPM`);
    if (item.intensity < 0 || item.intensity > 1) fail(`profile ${item.id} has invalid intensity`);
    if (item.transitionMs < 0) fail(`profile ${item.id} has invalid transitionMs`);
  }
  for (const item of registry.generations) {
    if (!profileIds.has(item.profile))
      fail(`${item.id} references unknown profile ${item.profile}`);
    if (item.generationPrompt.length > config.generator.captionLimit) {
      fail(`${item.id} prompt exceeds ${config.generator.captionLimit} characters`);
    }
    const absoluteFile = path.resolve(root, item.file);
    if (!absoluteFile.startsWith(path.join(root, "packages", "client", "public") + path.sep)) {
      fail(`${item.id} points outside the client public directory`);
    }
    try {
      const file = await stat(absoluteFile);
      if (!file.isFile() || file.size === 0) throw new Error("empty or not a file");
    } catch {
      fail(`${item.id} audio file is missing: ${item.file}`);
    }
  }

  const runtimeTracks = registry.generations.map((item) => ({
    id: item.id,
    title: item.title,
    author: "lindocara",
    src: item.src,
    profile: item.profile,
    duration: item.duration,
    loopable: item.loopable,
    seed: item.seed,
  }));
  const runtimeProfiles = config.profiles.map((item) => ({
    id: item.id,
    title: item.title,
    description: item.description,
    biomes: item.biomes,
    moods: item.moods,
    bpm: item.bpm,
    intensity: item.intensity,
    duration: item.duration,
    loopable: item.loopable,
    transitionMs: item.transitionMs,
    fallbackTrackIds: item.fallbackTrackIds,
  }));
  const source = formatTypeScript(`/**
 * Generated by scripts/build-music-catalog.ts from studio/musics/*.json.
 * Edit the JSON source or use \`python studio/studio.py music\`; do not edit this file.
 */
export const LINDOCARA_MUSIC_DNA = ${serialise({
    ...config.dna,
    mainMotif: config.mainMotif,
  })} as const;

export const MUSIC_PROFILES = ${serialise(runtimeProfiles)} as const;

export const GENERATED_MUSIC_TRACKS = ${serialise(runtimeTracks)} as const;
`);

  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = await readFile(outputPath, "utf8");
    } catch {
      fail("generated catalogue is missing; run yarn music:catalog");
    }
    if (current !== source) fail("generated catalogue drift; run yarn music:catalog");
    console.log("Music catalogue is current.");
    return;
  }
  await writeFile(outputPath, source, "utf8");
  console.log(
    `Wrote ${path.relative(root, outputPath)} (${runtimeTracks.length} generated tracks).`,
  );
}

await main();
