/**
 * Rasterises today's collision rectangles into tile data, once, so the tilemap can become the
 * source of truth without redesigning the world in the same commit.
 *
 * Run with: npm run map:build
 */
import { writeFileSync } from "node:fs";
import { OBSTACLES, type Rect, SAFE_ZONE } from "../src/shared/game.js";
import { VERDANT_REACH_BOUNDS, type WorldBounds } from "../src/shared/simulation.js";
import { TILE_SIZE, type TileKind } from "../src/shared/tilemap.js";
import { TEST_ZONE_TERRAIN } from "../src/shared/zones.js";

/**
 * How much of a cell must be blocked before the cell is a wall.
 *
 * Not "any overlap" (walls would fatten by up to 63px and swallow spawn points that today sit a
 * few pixels from a building), and not "entirely covered" (a 120px-thick wall could straddle cell
 * boundaries and vanish). Half is the rule that preserves both walls and the gaps between them.
 */
const SOLID_COVERAGE = 0.5;

function coverage(rects: readonly Rect[], col: number, row: number): number {
  const x0 = col * TILE_SIZE;
  const y0 = row * TILE_SIZE;
  let covered = 0;
  // Sample on a 8x8 sub-grid: exact enough at 64px, and immune to overlapping rects being
  // double-counted, which a naive area sum would get wrong.
  const STEPS = 8;
  const step = TILE_SIZE / STEPS;
  for (let sy = 0; sy < STEPS; sy++) {
    for (let sx = 0; sx < STEPS; sx++) {
      const px = x0 + (sx + 0.5) * step;
      const py = y0 + (sy + 0.5) * step;
      const hit = rects.some(
        (r) => px >= r.x && px < r.x + r.width && py >= r.y && py < r.y + r.height,
      );
      if (hit) covered++;
    }
  }
  return covered / (STEPS * STEPS);
}

function rasterise(
  bounds: WorldBounds,
  obstacles: readonly Rect[],
): {
  cols: number;
  rows: number;
  kinds: TileKind[];
} {
  const cols = Math.ceil(bounds.width / TILE_SIZE);
  const rows = Math.ceil(bounds.height / TILE_SIZE);
  const kinds: TileKind[] = [];
  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      kinds.push(coverage(obstacles, col, row) >= SOLID_COVERAGE ? "water" : "grass");
    }
  }
  return { cols, rows, kinds };
}

function emit(name: string, constant: string, data: ReturnType<typeof rasterise>): string {
  // One character per cell, one line per row: a 75-wide map stays readable and diffable in git,
  // and a hand edit in Tiled later shows up as a legible change rather than a wall of numbers.
  const CHAR: Record<TileKind, string> = { grass: ".", plateau: "^", water: "#", bridge: "=" };
  const rowsText = [];
  for (let row = 0; row < data.rows; row++) {
    const line = data.kinds
      .slice(row * data.cols, (row + 1) * data.cols)
      .map((k) => CHAR[k])
      .join("");
    rowsText.push(`  "${line}",`);
  }
  return `// GENERATED by scripts/build-map.ts — do not edit by hand. Run: npm run map:build

import type { TileMap } from "../tilemap.js";
import { decodeTileMap } from "../tilemap-codec.js";

const ROWS = [
${rowsText.join("\n")}
];

/** ${name} */
export const ${constant}: TileMap = decodeTileMap(ROWS);
`;
}

// Verdant Reach's height (2700) isn't a multiple of TILE_SIZE (64), so `rasterise` rounds up to
// 43 rows and the last one (row 42) straddles the world's real bottom edge — only its top 12px
// are inside the world at all. That sliver sits inside the 96px-thick bottom boundary wall
// (BOUNDARY_OBSTACLES / WORLD_BOUNDARY_DEPTH in game.ts) but doesn't reach the 50% coverage
// threshold on its own, so row 42 comes out all-grass rather than solid. It looks like a bug —
// an inexplicable strip of open ground — but it's inert: row 41 sits entirely inside that same
// wall and rasterises fully solid, sealing row 42 off, and clampToWorld never lets a player's y
// go far enough down for their box to clear row 41 in the first place. Left as-is on purpose;
// see "keeps the last row unreachable" in test/tilemap-data.test.ts, which pins both halves of
// why nobody will ever stand there.
const verdant = rasterise(VERDANT_REACH_BOUNDS, OBSTACLES);
writeFileSync(
  "src/shared/zones/verdant-reach-tiles.ts",
  emit("Verdant Reach", "VERDANT_REACH_TILES", verdant),
);

const test = rasterise(TEST_ZONE_TERRAIN, TEST_ZONE_TERRAIN.obstacles);
writeFileSync(
  "src/shared/zones/mmo-test-zone-tiles.ts",
  emit("Crossing Annex", "MMO_TEST_ZONE_TILES", test),
);

console.log(
  `verdant-reach ${verdant.cols}x${verdant.rows}, mmo-test-zone ${test.cols}x${test.rows}`,
);
console.log(`safe zone spans x ${SAFE_ZONE.x}..${SAFE_ZONE.x + SAFE_ZONE.width}`);
