// GENERATED by scripts/build-map.ts — do not edit by hand. Run: npm run map:build

import type { TileMap } from "../tilemap.js";
import { decodeTileMap } from "../tilemap-codec.js";

const ROWS = [
  "..........",
  "..........",
  "..........",
  ".....##...",
  ".....#....",
  "..........",
  "..........",
  "..........",
];

/** Crossing Annex */
export const MMO_TEST_ZONE_TILES: TileMap = decodeTileMap(ROWS);
